
CC=gcc

#CFLAGS+=-W -Wall -D_HAS_STRL_=1 -D_HAS_RDLN_=1
CFLAGS+=-W -Wall -D_HAS_RDLN_=1
LDFLAGS+=-lreadline

STD_CFLAGS=$(CFLAGS) -O2
STD_LDFLAGS=$(LDFLAGS) -s

DBG_CFLAGS=$(CFLAGS) -O0 -ggdb3 -I/usr/local/include
DBG_LDFLAGS=$(LDFLAGS) -lefence -L/usr/local/lib

SRCS=*.c

LISP_IMAGE=bin/LISP
LISP_IMAGE_DBG=$(LISP_IMAGE)_dbg
LISP_IMAGE_DBGALL=$(LISP_IMAGE)_dbgAll
LISP_IMAGE_DBGPARSER=$(LISP_IMAGE)_dbgParser
LISP_IMAGE_DBGLMI=$(LISP_IMAGE)_dbgLMI
LISP_IMAGE_DBGEVAL=$(LISP_IMAGE)_dbgEval

LISP_ALL_IMAGES= \
  $(LISP_IMAGE) \
  $(LISP_IMAGE_DBG) # \
#  $(LISP_IMAGE_DBGALL) \
#  $(LISP_IMAGE_DBGPARSER) \
#  $(LISP_IMAGE_DBGLMI) \
#  $(LISP_IMAGE_DBGEVAL)

DBGALL_CFLAGS=$(DBG_CFLAGS) -DDEBUG_PARSER -DDEBUG_LMI -DDEBUG_EVAL
DBGPARSER_CFLAGS=$(DBG_CFLAGS) -DDEBUG_PARSER
DBGLMI_CFLAGS=$(DBG_CFLAGS) -DDEBUG_LMI
DBGEVAL_CFLAGS=$(DBG_CFLAGS) -DDEBUG_EVAL


all:				$(LISP_ALL_IMAGES)

$(LISP_IMAGE):			$(SRCS)
	$(CC) $(STD_CFLAGS) -o $@ $(SRCS) $(STD_LDFLAGS)

$(LISP_IMAGE_DBG):		$(SRCS)
	$(CC) $(DBG_CFLAGS) -o $@ $(SRCS) $(DBG_LDFLAGS)

$(LISP_IMAGE_DBGALL):		$(SRCS)
	$(CC) $(DBGALL_CFLAGS) -o $@ $(SRCS) $(DBG_LDFLAGS)

$(LISP_IMAGE_DBGPARSER):	$(SRCS)
	$(CC) $(DBGPARSER_CFLAGS) -o $@ $(SRCS) $(DBG_LDFLAGS)

$(LISP_IMAGE_DBGLMI):		$(SRCS)
	$(CC) $(DBGLMI_CFLAGS) -o $@ $(SRCS) $(DBG_LDFLAGS)

$(LISP_IMAGE_DBGEVAL):		$(SRCS)
	$(CC) $(DBGEVAL_CFLAGS) -o $@ $(SRCS) $(DBG_LDFLAGS)

clean:
	rm -f $(LISP_ALL_IMAGES)

